### PR TITLE
allow django 4.2

### LINKED ISSUE #29: update feedstock to allow django 4.2
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The current recipe restricts the django dependency to <4.2, but this should be changed to <4.3:
https://github.com/conda-forge/django-simple-history-feedstock/blob/cdd4df19ee89b5b6d64bf4c7feaf7b6d21abf051/recipe/meta.yaml#L25

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### PR DESCRIPTION
**Pull request by jacksund**
- closes #29 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jacksund** [comment]
@conda-forge-admin, please rerender

**Comment by jacksund** [comment]
@rxm7706 this PR is ready. would you be able to review and merge?

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by jacksund** [comment]
@rxm7706 Thank you!

**Pull request merged**
