### PR TITLE
Update to Version 3.3.0

### LINKED ISSUE #20: Bump to version 3.0.0
### Comment:

Any chance we can get the package updated to verison 3.0.0 (currently available on PyPi)? There are some important bugfixes in there (https://github.com/jazzband/django-simple-history/issues/813 for me) that currently forced me to install via pip instead of conda :(

Happy to help if there is anything i can do!

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by williamjamir** [comment]
@conda-forge-admin, please rerun bot

**Comment by williamjamir** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please restart ci

**Comment by rxm7706** [comment]
@cshaley Build is successful, can you merge

**Comment by williamjamir** [comment]
@conda-forge/core could you merge this PR?

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
